apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app
  labels:
    app: node-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: 899500463010.dkr.ecr.us-east-1.amazonaws.com/repo:build-2a11ece4-d52a-4459-ac1c-ee4cbd12e151
          resources:
            requests:
              memory: "12Mi"
              cpu: "50m"
            limits:
              memory: "25Mi"
              cpu: "100m"
          ports:
            - containerPort: 80
